-- Safe Supabase/Postgres migration for the cold email app
-- This script is idempotent and avoids problematic constraint re-creation.

CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  website TEXT,
  contact_email TEXT,
  phone TEXT,
  all_emails TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT
);

CREATE TABLE IF NOT EXISTS drafts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  subject TEXT,
  body TEXT,
  research_summary TEXT,
  offer TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  error TEXT,
  sent_at TEXT,
  scheduled_at TEXT,
  scheduled_tz TEXT,
  message_id TEXT,
  sender_key TEXT,
  sender_name TEXT,
  sender_email TEXT,
  replied_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
  tracking_id TEXT,
  opened_at TEXT,
  open_count INTEGER DEFAULT 0,
  last_opened_at TEXT,
  clicked_at TEXT,
  click_count INTEGER DEFAULT 0,
  last_clicked_at TEXT
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS replies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  draft_id INTEGER REFERENCES drafts(id) ON DELETE SET NULL,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  from_email TEXT,
  subject TEXT,
  snippet TEXT,
  imap_message_id TEXT UNIQUE,
  status TEXT DEFAULT 'new',
  notes TEXT,
  received_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT
);

DO $$
BEGIN
  -- If the tables already exist from a prior partial setup, add any missing columns safely.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'scheduled_at'
  ) THEN
    ALTER TABLE drafts ADD COLUMN scheduled_at TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'scheduled_tz'
  ) THEN
    ALTER TABLE drafts ADD COLUMN scheduled_tz TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'companies' AND column_name = 'phone'
  ) THEN
    ALTER TABLE companies ADD COLUMN phone TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'companies' AND column_name = 'all_emails'
  ) THEN
    ALTER TABLE companies ADD COLUMN all_emails TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'message_id'
  ) THEN
    ALTER TABLE drafts ADD COLUMN message_id TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'sender_key'
  ) THEN
    ALTER TABLE drafts ADD COLUMN sender_key TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'sender_name'
  ) THEN
    ALTER TABLE drafts ADD COLUMN sender_name TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'sender_email'
  ) THEN
    ALTER TABLE drafts ADD COLUMN sender_email TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'replied_at'
  ) THEN
    ALTER TABLE drafts ADD COLUMN replied_at TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'tracking_id'
  ) THEN
    ALTER TABLE drafts ADD COLUMN tracking_id TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'opened_at'
  ) THEN
    ALTER TABLE drafts ADD COLUMN opened_at TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'open_count'
  ) THEN
    ALTER TABLE drafts ADD COLUMN open_count INTEGER DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'last_opened_at'
  ) THEN
    ALTER TABLE drafts ADD COLUMN last_opened_at TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'clicked_at'
  ) THEN
    ALTER TABLE drafts ADD COLUMN clicked_at TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'click_count'
  ) THEN
    ALTER TABLE drafts ADD COLUMN click_count INTEGER DEFAULT 0;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'drafts' AND column_name = 'last_clicked_at'
  ) THEN
    ALTER TABLE drafts ADD COLUMN last_clicked_at TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'replies' AND column_name = 'status'
  ) THEN
    ALTER TABLE replies ADD COLUMN status TEXT DEFAULT 'new';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'replies' AND column_name = 'notes'
  ) THEN
    ALTER TABLE replies ADD COLUMN notes TEXT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_drafts_company_id ON drafts(company_id);
CREATE INDEX IF NOT EXISTS idx_drafts_status ON drafts(status);
CREATE INDEX IF NOT EXISTS idx_drafts_tracking_id ON drafts(tracking_id);
CREATE INDEX IF NOT EXISTS idx_replies_draft_id ON replies(draft_id);
CREATE INDEX IF NOT EXISTS idx_replies_company_id ON replies(company_id);

-- Atomic open tracking (no race condition)
CREATE OR REPLACE FUNCTION track_open(p_tracking_id TEXT, p_now TIMESTAMPTZ)
RETURNS void LANGUAGE sql AS $$
  UPDATE drafts
  SET
    open_count     = COALESCE(open_count, 0) + 1,
    opened_at      = COALESCE(opened_at, p_now),
    last_opened_at = p_now
  WHERE tracking_id = p_tracking_id;
$$;

-- Atomic click tracking (no race condition)
CREATE OR REPLACE FUNCTION track_click(p_tracking_id TEXT, p_now TIMESTAMPTZ)
RETURNS void LANGUAGE sql AS $$
  UPDATE drafts
  SET
    click_count     = COALESCE(click_count, 0) + 1,
    clicked_at      = COALESCE(clicked_at, p_now),
    last_clicked_at = p_now
  WHERE tracking_id = p_tracking_id;
$$;

-- Grant execute to anon role so the JS client can call them
GRANT EXECUTE ON FUNCTION track_open(TEXT, TIMESTAMPTZ) TO anon;
GRANT EXECUTE ON FUNCTION track_click(TEXT, TIMESTAMPTZ) TO anon;
