-- Supabase PostgreSQL migration for cold-email-tool
-- Matches local database schema exactly with PostgreSQL identity columns and defaults

CREATE TABLE IF NOT EXISTS companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  website TEXT,
  contact_email TEXT,
  phone TEXT,
  all_emails TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT
);

CREATE TABLE IF NOT EXISTS drafts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  subject TEXT,
  body TEXT,
  research_summary TEXT,
  offer TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  error TEXT,
  sent_at TEXT,
  scheduled_at TEXT,
  scheduled_tz TEXT,
  message_id TEXT,
  sender_key TEXT,
  sender_name TEXT,
  sender_email TEXT,
  replied_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
  tracking_id TEXT,
  opened_at TEXT,
  open_count INTEGER DEFAULT 0,
  last_opened_at TEXT,
  clicked_at TEXT,
  click_count INTEGER DEFAULT 0,
  last_clicked_at TEXT
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS replies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  draft_id INTEGER REFERENCES drafts(id) ON DELETE SET NULL,
  company_id INTEGER REFERENCES companies(id) ON DELETE SET NULL,
  from_email TEXT,
  subject TEXT,
  snippet TEXT,
  imap_message_id TEXT UNIQUE,
  status TEXT DEFAULT 'new',
  notes TEXT,
  received_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT
);

CREATE INDEX IF NOT EXISTS idx_drafts_company_id ON drafts(company_id);
CREATE INDEX IF NOT EXISTS idx_drafts_status ON drafts(status);
CREATE INDEX IF NOT EXISTS idx_drafts_tracking_id ON drafts(tracking_id);
CREATE INDEX IF NOT EXISTS idx_replies_draft_id ON replies(draft_id);
CREATE INDEX IF NOT EXISTS idx_replies_company_id ON replies(company_id);

-- Disable Row Level Security (RLS) or enable full access policies for app tables
ALTER TABLE public.companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.drafts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.replies DISABLE ROW LEVEL SECURITY;
